### ISSUE TITLE
Adyen 8 | Ensure payment profile record created via SP API when checking with subscription, with Adyen CC

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-adyen#10]
If I use the subscribepro/subscribepro-magento2-offline-payments module I can add adyen_cc to the list of allowed offline payment methods and force the adyen payment methods to display in checkout.

When I do this, and create a subscription no payment profile is created.

![adyen_sub_no_pp](https://github.com/subscribepro/subscribepro-magento2-adyen/assets/1232258/e67557d4-c614-4d45-be76-825d34158d8b)

**Comment by garthbrantley** [comment]
This is believed to be resolved by #11
