### ISSUE TITLE
Credit cards stored with SUBSCRIPTION type should be available to customer for future purchases.

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-adyen#17]
In https://github.com/Adyen/adyen-magento2/blob/develop/Plugin/CustomerFilterVaultTokens.php the SUBSCRIPTION type tokens are being filtered out of the list available for customer checkout.

**Comment by czettnersandor** [comment]
Done in this PR: https://github.com/subscribepro/subscribepro-magento2-adyen/pull/22/files
