### ISSUE TITLE
Support Adyen 8.21.0 (Or possibly 8.22.x)

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-adyen#8]
## Overview
Subscribe Pro shall modify the Subscribe Pro <> Magento 2 <> Adyen connector extension (https://github.com/subscribepro/subscribepro-magento2-adyen) to add support for the Adyen Magento 2 extension version 8.21.0 (https://github.com/Adyen/adyen-magento2/releases/tag/8.21.0).

## Adyen 8 M2 Extension Configuration

The following configuration settings are required for the Adyen 8 M2 extension under **Card Tokenization**:

* **Enabled** = Yes
* **Mode** = Magento Vault
* **Require CVC** = Yes
* **Token Type** = Subscription

![image](https://github.com/subscribepro/subscribepro-magento2-adyen/assets/8466130/d195d5b7-16c3-4cf1-b19c-d4d47237e408)

## Development Specifications and Requirements
Subscribe Pro shall modify the Subscribe Pro <> Magento 2 <> Adyen connector extension to meet the following requirements:
- The following combination of other module versions shall be supported:
  - Magento 2 version 2.4.5 or 2.4.6
  - Subscribe Pro Magento 2 extension version 1.6.0
  - Adyen Magento 2 extension version 8.21.0
- Subscribe Pro shall modify the Adyen connector extension and publish an updated version at:
  - https://github.com/subscribepro/subscribepro-magento2-adyen
- Updated connector extension shall support credit card payment methods, tokenized via the Adyen payments API
- Updated connector extension shall support all current features which are available when used with Adyen Magento 2 extension version 7.3.6
- Updated connector extension shall support Subscribe Pro environments configured to work with Magento 2 with the following configuration:
  - “Custom External Vault” payment vault used
  - “Magento 2 Order Callback” e-commerce platform connection type used

### (Adyen 7) Initial checkout / sign up for subscription - customer saved new credit card

When configured per specifications above, the Adyen API request / response should look as follows (some fields are anonymized with `XXXX` and some ommitted with `...`:

Request to `https://checkout-test.adyen.com/checkout/v67/payments`:

```json
{
  "merchantAccount": "XXXX",
  "shopperReference": "XXX",
  "shopperEmail": "testseanh.nhs+1003x@gmail.com",
  "telephoneNumber": "(111) 111-1111",
  "shopperName": {
...
  },
  "countryCode": "US",
  "shopperLocale": "en_US",
  "shopperIP": "165.225.38.83",
  "billingAddress": {
...
  },
  "deliveryAddress": {
...
  },
  "amount": {
    "currency": "USD",
    "value": 3493
  },
  "reference": "000006149",
  "fraudOffset": "0",
  "browserInfo": {
...
  },
  "storePaymentMethod": true,
  "recurringProcessingModel": "Subscription",
  "shopperInteraction": "Ecommerce",
  "paymentMethod": {
    "type": "scheme",
    "holderName": "XXX",
    "encryptedCardNumber": "XXXX",
    "encryptedExpiryMonth": "XXXX",
    "encryptedExpiryYear": "XXXX",
    "encryptedSecurityCode": "XXXX",
    "brand": "discover"
  },
  "riskData": {
    "clientData": "XXXX"
  },
  "additionalData": {
    "allow3DS2": true
  },
  "returnUrl": "XXXX",
  "channel": "web",
  "origin": "XXXX",
  "applicationInfo": {
    "adyenLibrary": {
      "name": "adyen-php-api-library",
      "version": "10.1.0"
    },
    "externalPlatform": {
      "version": "2.4.6",
      "name": "Magento"
    },
    "merchantApplication": {
      "version": "7.3.8",
      "name": "adyen-magento2"
    }
  }
}
```

Response:

```json
{
  "additionalData": {
...
    "recurring.recurringDetailReference": "XXXX",
    "recurringProcessingModel": "Subscription",
    "threeDAuthenticated": "false",
    "merchantReference": "000006149",
...
    "recurring.shopperReference": "25655",
    "fundingSource": "CREDIT"
  },
  "pspReference": "XXXX",
  "resultCode": "Authorised",
  "amount": {
    "currency": "USD",
    "value": 3493
  },
  "merchantReference": "000006149"
}
```

### (Adyen 8) Initial checkout / sign up for subscription - customer saved new credit card

```json
{
  "apiVersion": "v70",
  "body": {
    "merchantAccount": "XXXX",
    "shopperReference": "002",
    "shopperEmail": "test@test.com",
    "telephoneNumber": "1231231234",
    "shopperName": {
      "firstName": "Test",
      "lastName": "User"
    },
    "countryCode": "US",
    "shopperLocale": "en_US",
    "shopperIP": "172.24.0.1",
    "billingAddress": {
...  
  },
    "deliveryAddress": {
...
    },
    "amount": {
      "currency": "USD",
      "value": 3700
    },
    "reference": "000000021",
    "fraudOffset": "0",
    "browserInfo": {
...
    },
    "storePaymentMethod": true,
    "recurringProcessingModel": "Subscription",
    "shopperInteraction": "Ecommerce",
    "paymentMethod": {
      "type": "scheme",
      "holderName": "",
      "encryptedCardNumber": "XXXX",
      "encryptedExpiryMonth": "XXXX",
      "encryptedExpiryYear": "XXXX",
      "encryptedSecurityCode": "XXXX",
      "brand": "mc",
      "checkoutAttemptId": "XXXX"
    },
    "riskData": {
      "clientData": "XXXX"
    },
    "additionalData": {
      "allow3DS2": true
    },
    "returnUrl": "XXXX",
    "channel": "web",
    "origin": "XXXX"
  }
}
```

Response:

```json
{
  "body": {
    "additionalData": {
      "expiryDate": "3/2030",
      "cardBin": "222240",
      "cardHolderName": "Checkout Shopper PlaceHolder",
      "cardSummary": "0005",
      "recurring.recurringDetailReference": "XXXX",
      "recurringProcessingModel": "Subscription",
      "paymentMethod": "mc",
      "recurring.shopperReference": "002"
    },
    "pspReference": "XXXX",
    "resultCode": "Authorised",
    "amount": {
      "currency": "USD",
      "value": 3700
    },
    "merchantReference": "000000021",
    "paymentMethod": {
      "brand": "mc",
      "type": "scheme"
    }
  }
}
```

### (Adyen 8) - TBD - Recurring Order - Triggered by SP platform, via M2 API, customer not present, existing saved credit card

When SP triggers recurring orders (or off-cycle orders) via the M2 API, the Adyen payment request / response needs to look as follows:

Request to `/payments`:

```json
{
  "apiVersion": "v70",
  "body": {
    "merchantAccount": "XXXX",
    "shopperReference": "002",
    "shopperEmail": "test@test.com",
    "telephoneNumber": "1231231234",
    "shopperName": {
      "firstName": "Test",
      "lastName": "User"
    },
    "countryCode": "US",
    "shopperLocale": "en_US",
    "shopperIP": null,
    "billingAddress": {
...
    },
    "deliveryAddress": {
...
    },
    "amount": {
      "currency": "USD",
      "value": 3700
    },
    "reference": "000000023",
    "fraudOffset": "0",
    "returnUrl": "XXXX",
    "channel": "web",
    "origin": "XXXX",
    "paymentMethod": {
      "type": "scheme",
      "holderName": "",
      "storedPaymentMethodId": "XXXX",  # Should be payment token which was stored in M2 vault record, which corresponds to `recurring.recurringDetailReference` field from the original response
      "brand": "mc",
      "checkoutAttemptId": "XXXX"
    },
    "recurringProcessingModel": "Subscription",
    "shopperInteraction": "ContAuth"
  }
}
```

## Simulating Recurring Order

We simulated the recurring order payment by doing the following:

1. Modify Adyen 8 M2 extension code. Comment out **line 37** in `/Plugin/CustomerFilterVaultTokens.php`:

```php
    public function afterGetCustomerSessionTokens(
        CustomerTokenManagement $customerTokenManagement,
        array $customerSessionTokens
    ): array {
        foreach ($customerSessionTokens as $key => $token) {
            if (strpos($token->getPaymentMethodCode(), 'adyen_') === 0) {
                $tokenDetails = json_decode($token->getTokenDetails());
                if (property_exists($tokenDetails, Vault::TOKEN_TYPE) &&
                    in_array($tokenDetails->tokenType, [
//                        Recurring::SUBSCRIPTION,
                        Recurring::UNSCHEDULED_CARD_ON_FILE]
                    )
                ) {
                    unset($customerSessionTokens[$key]);
                }
            }
        }

        return $customerSessionTokens;
    }
```

2. **Temporily** Set **Require CVC** to No.

4. Checkout on front-end of site as customer, choose the saved credit card which was saved with above configuration.

**Comment by czettnersandor** [comment]
This is ready for testing: https://github.com/subscribepro/subscribepro-magento2-adyen/pull/15

The issue was a bug at Adyen's side in Adyen\Payment\Gateway\Request\RecurringVaultDataBuilder. 

`if ($paymentMethod->getCode() !== AdyenCcConfigProvider::CC_VAULT_CODE) {`
Should have been:
`if ($paymentMethod->getCode() === AdyenCcConfigProvider::CC_VAULT_CODE) {`

After creating a plugin around this method call, reorders are working from Subscribepro. Otherwise, it would never assign 'paymentMethod' object to the request body for adyen_cc_vault code. Reorder using the hack provided in the ticket works, because the CVC is present in the request. While from API, it's not.
